### ISSUE TITLE
Cannot save setting

### ISSUE THREAD

**Issue by kingfisher77** [linuxserver/docker-unifi-controller#35] opened 2020-03-01 21:51 UTC
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior

Setting should be saved and persistent.

## Current Behavior

Settings are not saved and not persistent.

## Steps to Reproduce

1. Does not matter which settings, nothing is saved.
2.
3.
4.

## Environment
**OS:**

CentOS 8.1

**CPU architecture:** x86_64/arm32/arm64      

x86_64

**How docker service was installed:**      

docker-compose

## Command used to create docker container (run/create/compose/screenshot)

docker-compose up -d

## Docker logs

root@service1:~/work/unifi # docker logs unifi-controller
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    993
User gid:    990
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

**Comment by CHBMB** [comment] 2020-03-01 22:13
You need to post your compose file, not the command to bring it up.

**Comment by kingfisher77** [comment] 2020-03-02 07:46
Thank you, meanwhile i realized that CentOS 8 and Docker needs some extra tweaking because DNS is not available inside the container without extra measures. Will come back with my findings.

**Comment by kingfisher77** [comment] 2020-03-02 11:41
To enable internet access from within the docker container on centos 8 it is necessary to activate masquerading in firewalld. Now firmware update check with the controller gui is working. What is still not working is making changes of settings with the GUI.

More precise tests brought up that *only* saving of setting in the section "User Interface" and "Try new settings" are not saved and show up an error message (with green check ...). Changes of settings like in  "Site" are fine.  

Used docker-compose.yml:

---
version: "2"
services:
  unifi-controller:
    image: linuxserver/unifi-controller
    container_name: unifi-controller
    environment:
      - PUID=993
      - PGID=990
      - MEM_LIMIT=1024M #optional
    volumes:
      - /docker/unifi/config:/config:rw
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8081:8081
      - 8443:8443
      - 8843:8843
      - 8880:8880
      - 6789:6789
    restart: unless-stopped
#volumes:
#  unifi-config:

server.log and mongod.log do not show up any errors or strange things.

**Comment by kingfisher77** [comment] 2020-03-02 11:43
What could i test? Where to increase debug level?

**Comment by kingfisher77** [comment] 2020-03-02 12:23
Increased debug in system.properties

```
debug.device=debug
debug.mgmt=debug
debug.sdn=debug
debug.system=debug
```

Interesting log output about everything but nothing when i press the save button...

**Comment by aptalca** [comment] 2020-03-02 12:32
What setting are you trying to change?

**Comment by kingfisher77** [comment] 2020-03-02 12:36
For example
Preferences>Formatting>Use 24-Hour Time

A flyout with this message appears:
SETTINGS_CONTROLLER_UI_SAVE_ERROR

Messages are different depending on which tab in preferences i use.

**Comment by kingfisher77** [comment] 2020-03-02 12:57
Also changing password is not working:

`There was an error updating your account.`

**Comment by kingfisher77** [comment] 2020-03-02 13:04
In the client browser an error is visible by saving a preference which does not save.
It is the last one "Put" which appears directly after saving:
https://drive.google.com/file/d/1RH9K0vFzmGcFYW2tD8_Lu87L_A1ty_mC

**Comment by kingfisher77** [comment] 2020-03-02 14:19
It seems that the error ls located in nginx proxy. If i open up firewalld port 8443 and use firefox as browser with port :8443 then i can save all settings.

My nginx proxy:

```
      location / {
                proxy_pass https://localhost:8443;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header Host $http_host;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
                proxy_ssl_verify off;
        }
```

Any ideas what i can try?

**Comment by aptalca** [comment] 2020-03-02 14:26
Well, you failed to mention you're accessing through a reverse proxy

We can't reproduce these errors. They are most likely related to your reverse proxy config. Our letsencrypt image has a working config you can use for reference: https://github.com/linuxserver/reverse-proxy-confs/blob/master/unifi-controller.subdomain.conf.sample

In any case, this is not a bug, so closing this issue. Feel free to use discord or the forum for further questions.

**Closed by aptalca** 2020-03-02 14:26 UTC
Labels: invalid
