### ISSUE TITLE
[BUG] JVM error with 7.3.76

### ISSUE THREAD

**Issue by GodAtum360** [linuxserver/docker-unifi-controller#180] opened 2022-12-10 18:12 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When updating to 7.3.76 I get an error

`Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Invalid maximum heap size: -Xmx1024MM`

You might want to update your install instructions for the heap size environment variable.

### Steps To Reproduce

Updating docker image to 7.3.76.

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
---
version: "2.1"
services:
  unifi-controller:
    image: ghcr.io/linuxserver/unifi-controller:version-7.3.76
    container_name: unifi-controller
    environment:
      - PUID=1000
      - PGID=1000

    volumes:
      - /home/rancher/docker_volumes/unifi-controller/config:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8443:8443
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
      - 1611:161/udp #SNMP
    restart: unless-stopped
```

### Container logs

```bash
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Invalid maximum heap size: -Xmx1024MM
```

**Comment by thespad** [comment] 2022-12-10 18:14
Duplicate of https://github.com/linuxserver/docker-unifi-controller/issues/168

**Closed by thespad** 2022-12-10 18:14 UTC
