### ISSUE TITLE
Huge amount of WiredTigerLog.xxxxxxxxxx files in data/db/journal/

### ISSUE THREAD

**Issue by majbom** [linuxserver/docker-unifi-controller#102] opened 2021-11-11 21:28 UTC
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

I dont think 10+ 100 MB files every minute is normal behavior

## Current Behavior

When the docker is running, there's generated 10+ 100 MB files named "WiredTigerLog.xxxxxxxxxx" (x: 0000000001, 0000000002, 00000003 etc.)

## Steps to Reproduce

The problem started after the latest update
UI: 6.4.54.0
Backend: 6.4.54
Build: atag_6.4.54_16067

## Environment
**OS:** Unraid OS
**CPU architecture:** x64
**How docker service was installed:** Through "Community Applications"

## Command used to create docker container (run/create/compose/screenshot)

![image](https://user-images.githubusercontent.com/12933472/141371537-fc102fd8-9631-4534-9131-271aa78a30ef.png)

## Docker logs

# docker logs unifi-controller
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    99
User gid:    100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing... 

Warning:
The JKS keystore uses a proprietary format. It is recommended to migrate to PKCS12 which is an industry standard format using "keytool -importkeystore -srckeystore /config/data/keystore -destkeystore /config/data/keystore -deststoretype pkcs12".
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
WARN Unable to load properties from '/usr/lib/unifi/data/system.properties' - /usr/lib/unifi/data/system.properties (No such file or directory)
org.tuckey.web.filters.urlrewrite.UrlRewriteFilter INFO: destroy called
Exception in thread "Thread-14" java.lang.IllegalStateException: BeanFactory not initialized or already closed - call 'refresh' before accessing beans via the ApplicationContext
        at org.springframework.context.support.AbstractRefreshableApplicationContext.getBeanFactory(AbstractRefreshableApplicationContext.java:168)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1172)
        at com.ubnt.service.C.Ö00000(Unknown Source)
        at com.ubnt.ace.Launcher.Ò00000(Unknown Source)
        at java.lang.Thread.run(Thread.java:748)
org.tuckey.web.filters.urlrewrite.UrlRewriteFilter INFO: destroy called
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    99
User gid:    100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing... 
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

**Comment by majbom** [comment] 2021-11-24 15:41
It seems to be fixed in the newest version

**Comment by burkasaurusrex** [comment] 2021-12-14 08:17
I continue to have the issue on and off. I'll try to isolate the cause but there's nothing that's obvious.

**Comment by the-lazy-fox** [comment] 2021-12-25 22:55
Same here

**Comment by the-lazy-fox** [comment] 2022-01-08 13:04
Same for me and its still happening today with the latest version (lscr.io/linuxserver/unifi-controller:latest).

Behavior is the following: /data/db/journal is growing until the machine crashes...

**Comment by the-lazy-fox** [comment] 2022-02-08 07:11
Issue solved on my side, it's due to the switch to the new interface.
You have now a settings to customize the log retention. 
Reduce it @majbom @burkasaurusrex and it will solve the issue.

**Comment by j0nnymoe** [comment] 2022-07-31 15:36
Closing as solution was provided.

**Closed by j0nnymoe** 2022-07-31 15:36 UTC
Labels: no-issue-activity

**Comment by RJGamer1002** [comment] 2022-12-15 05:48
i'm having the same issue also. my journal locations has 2 tb!! of those files I'm going to manually remove them or at least try to
