### ISSUE TITLE
Publish tag :6 to pin major version

### ISSUE THREAD

**Issue by ItalyPaleAle** [linuxserver/docker-unifi-controller#99] opened 2021-10-12 21:27 UTC
As per title, could you please publish a tag such as `linuxserver/unifi-controller:6` that always maps to the latest version in the 6 branch?

Currently, `:latest` will always upgrade to the latest version, and using `:latest` is considered a bad practice. When UniFi Controller version 7 comes out, I don't want the system to update itself automatically, before I can run some tests.

**Comment by ItalyPaleAle** [comment] 2021-10-13 01:46
Sounds good, thanks for sharing that.

May I suggest updating the README to clarify that using `latest` is strongly discouraged then? For example, the examples do not specify any tags and that defaults to using `latest`, which is perhaps the worst practice: https://github.com/linuxserver/docker-unifi-controller#usage

**Comment by aptalca** [comment] 2021-10-13 01:54
I didn't say do not use `latest`. You can use `latest.` But don't let anything auto update. When you do update, make sure you have a backup in case something breaks. And always make sure you're watching when something is updated so you can act on it if something breaks.

Here's what I use for versioned backups: https://www.linuxserver.io/blog/2019-10-01-updating-and-backing-up-docker-containers-with-version-control
With something like that, you can go back to the exact same working state if needed.

**Comment by drizuid** [comment] 2021-12-22 17:03
closing this as the requested action has always been in place, issue was caused by blind auto updating.

**Closed by drizuid** 2021-12-22 17:03 UTC
Labels: no-issue-activity
