### ISSUE TITLE
Blanc page when using Nginx Proxy Manager after update to 7.0.25-ls146

### ISSUE THREAD

**Issue by sowilo-be** [linuxserver/docker-unifi-controller#134] opened 2022-03-29 19:16 UTC
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

I use Nginx proxy to forward https://IP:8443 to https://unifi.something.local

## Current Behavior

Now it only shows a blanc page with below URL:

https://unifi.something.local/manage/account/login?redirect=%2Fmanage

https://IP:8443 and via the Unifi app does still work. Jus unable to proxy.
Tried to disable HSTS, web socket, caching, ... nothing works
All other services on the proxy do work perfectly fine.

## Steps to Reproduce

1) Deploy via Portainer and Docker compose stack
2) Configure forward in Nginx Proxy Manager
3) Configure dns rule to rewrite https://unifi.something.local/ to ip of nginx proxy manager
4) Surf to https://unifi.something.local/

## Environment
**OS:** Raspbian OS / Debian
**CPU architecture:** x86_64/arm32/arm64 ARM64
**How docker service was installed:** Official Repo

## Command used to create docker container (run/create/compose/screenshot)
Exactly the same as in the install instructions

## Docker logs

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.

[s6-init] ensuring user provided files have correct perms...exited 0.

[fix-attrs.d] applying ownership & permissions fixes...

[fix-attrs.d] done.

[cont-init.d] executing container initialization scripts...

[cont-init.d] 01-envfile: executing... 

[cont-init.d] 01-envfile: exited 0.

[cont-init.d] 01-migrations: executing... 

[migrations] started

[migrations] no migrations found

[cont-init.d] 01-migrations: exited 0.

[cont-init.d] 02-tamper-check: executing... 

[cont-init.d] 02-tamper-check: exited 0.

[cont-init.d] 10-adduser: executing... 

-------------------------------------

          _         ()

         | |  ___   _    __

         | | / __| | |  /  \

         | | \__ \ | | | () |

         |_| |___/ |_|  \__/

Brought to you by linuxserver.io

-------------------------------------

To support LSIO projects visit:

https://www.linuxserver.io/donate/

-------------------------------------

GID/UID

-------------------------------------

User uid:    1000

User gid:    1000

-------------------------------------

[cont-init.d] 10-adduser: exited 0.

[cont-init.d] 15-install: executing... 

*** installing unifi packages ***

Selecting previously unselected package unifi.

(Reading database ... 8986 files and directories currently installed.)

Preparing to unpack /app/unifi.deb ...

Unpacking unifi (7.0.25-17292-1) ...

Setting up unifi (7.0.25-17292-1) ...

invoke-rc.d: could not determine current runlevel

invoke-rc.d: policy-rc.d denied execution of start.

[cont-init.d] 15-install: exited 0.

[cont-init.d] 19-deprecate: executing... 

[cont-init.d] 19-deprecate: exited 0.

[cont-init.d] 20-config: executing... 

*** Setting Java memory limit to 1024M ***

*** Setting Java memory minimum to 1024M ***

[cont-init.d] 20-config: exited 0.

[cont-init.d] 30-keygen: executing... 

[cont-init.d] 30-keygen: exited 0.

[cont-init.d] 90-custom-folders: executing... 

[cont-init.d] 90-custom-folders: exited 0.

[cont-init.d] 99-custom-scripts: executing... 

[custom-init] no custom files found exiting...

[cont-init.d] 99-custom-scripts: exited 0.

[cont-init.d] done.

[services.d] starting services

[services.d] done.

**Comment by aptalca** [comment] 2022-03-29 19:26
This is not a bug with this image. You need to seek support with regards to npm. You can use our other support channels for community support since we don't officially support npm. Fwiw, unifi reverse proxy works with our supported method, which is SWAG.

Closing.

**Closed by aptalca** 2022-03-29 19:26 UTC
